### ISSUE TITLE
Could not load...

### ISSUE THREAD

**Issue by InspectorGadget** [InspectorGadget/CommandTracker#1]
`2017-01-09 [09:27:00]  [Server thread/INFO]: Loading source plugin CommandTracker v1.0.0
2017-01-09 [09:27:00]  [Server thread/CRITICAL]: Could not load plugin 'CommandTracker'`

**Comment by InspectorGadget** [comment]
![capture](https://cloud.githubusercontent.com/assets/20971020/21761682/8b919a9a-d68f-11e6-8e81-504ea76d6a68.PNG)

**Comment by InspectorGadget** [comment]
#2 Fixed it... Thanks

**Comment by HBIDamian** [comment]
Sidenote:
I personally would also use "logs.yml" instead of "logs.txt". Sometimes a text tile can get a little.... touchy.
I suggest you try them both. and see which one suits the needs of the plugin.

**Comment by InspectorGadget** [comment]
Alright
