### ISSUE TITLE
doesn't send to discord

### ISSUE THREAD

**Issue by ghost** [InspectorGadget/CommandTracker#7]
i set everything and i put the channel link in the config but it didn't work

**Comment by InspectorGadget** [comment]
Hi. Thank you for reporting the issue.

However, I have identified the issues where Discord has enforced Header type of their Webhook POST Payload. Please refer to this [`Gist`](https://gist.github.com/InspectorGadget/880fb2702854f4f2de9775646e50c72b).

I've also pushed a Commit which fixes this.
